name: Build and Push Docker Image

on:
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      ngs_bits_version:
        description: 'NGS-bits version (tag or branch) to build'
        required: false
        default: 'master'
      docker_tag:
        description: 'Docker tag for the image (defaults to latest or git tag)'
        required: false

  # Trigger on pushing tags (e.g., v1.0.0, 2025_01)
  push:
    tags:
      - '*' # Push on every tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        arch: [amd64, arm64]
    permissions:
      contents: read # Needed to check out the repository
      packages: write # Needed to push Docker images (though we push to Docker Hub here)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: benekenobi/ngs-bits
          tags: |
            # Handle tag push event (use the git tag, e.g., v1.2.3)
            type=ref,event=tag
            # Handle manual trigger tag input if provided
            type=raw,value=${{ github.event.inputs.docker_tag }},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.docker_tag != '' }}
            # Handle manual trigger, tag as 'master' if building master and no explicit tag given
            type=raw,value=master,enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.docker_tag == '' && (github.event.inputs.ngs_bits_version == 'master' || github.event.inputs.ngs_bits_version == '') }}

      - name: Determine NGS-bits Version
        id: ngs_version
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            # Use the Git tag for tag pushes
            echo "ngs_bits_version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            # Use the input for workflow_dispatch, defaulting to 'master'
            echo "ngs_bits_version=${{ github.event.inputs.ngs_bits_version || 'master' }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.arch }} # Use matrix arch here
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NGS_BITS_VERSION=${{ steps.ngs_version.outputs.ngs_bits_version }}
          cache-from: type=gha,scope=${{ matrix.arch }} # Scope cache per architecture
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }} # Scope cache per architecture

